// Dados dos produtos organizados por categoria
export const productCategories = [
  {
    id: 1,
    name: "Minimalista",
    slug: "minimalista",
    description: "Linha de produtos com design clean e linhas minimalistas",
  },
  {
    id: 2,
    name: "Conceito",
    slug: "conceito",
    description: "Produtos conceituais com tecnologia avançada",
  },
  {
    id: 3,
    name: "Clássica",
    slug: "classica",
    description: "Linha clássica com acabamentos de alta qualidade",
  },
  {
    id: 4,
    name: "Corporativo",
    slug: "corporativo",
    description: "Linha corporativa com acabamentos de alta qualidade",
  },
  {
    id: 4,
    name: "Complementares",
    slug: "complementares",
    description: "Linhas complementares",
  },
]

export const products = [
  // Categoria Minimalista
  {
    id: 1,
    name: "FEAL SLIM GLASS 30",
    slug: "feal-slim-glass-30",
    category: "minimalista",
    categoryId: 1,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/feal-slim-30-hero.jpg",
    price: "R$ 2.850,00",
    description: "Minimalista | Tecnologia Correr e Fixo",
    integration: "FEAL Slim Glass 50 e 60",
    intdescrp: "Complementos como pinázios, ripados ou muxarabis, mantendo linguagem arquitetônica",
    titledesc: "Transparência que valoriza o essencial",
    fullDescription:
      "A Feal Slim Glass 30 foi desenvolvida para projetos que exigem mais do que estética. Seu perfil ultradelgado permite ampla entrada de luz natural, garantindo conexão visual entre ambientes internos e externos, com total discrição estrutural. Ideal para residências que valorizam integração, leveza e modernidade. Essa solução une design funcional a um sistema técnico de alta performance  discreto no olhar, fino nos detalhes.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas técnicas que contribuem para isolamento termoacústico", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "22mm x 30mm" },
      { label: "Espessura do vidro", value: "8, 10, 12 e 14mm" },
      { label: "Acabamentos disponíveis", value: "Pintura eletrostática | Anodização | Efeito madeira" },
      { label: "Tipologias", value: "Correr | Fixo" },
      { label: "Complementos compatíveis", value: "Persiana entre vidros, tela mosquiteiras tensionadas e plissadas" },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 2,
    name: "FEAL SLIM GLASS 50",
    slug: "feal-slim-glass-50",
    category: "minimalista",
    categoryId: 1,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/feal-slim-50-hero.jpg",
    price: "R$ 3.200,00",
    description: "Minimalista | Tipologia: Correr e Fixo",
    integration: "Sistemas Feal Slim Glass 30 e Feal Slim Glass 60 para continuidade estética",
    intdescrp: "Complementos externos como sistema camarão, brises, entre outros, mantendo a linguagem arquitetônica",
    titledesc: "Equilíbrio entre leveza e desempenho",
    fullDescription:
      "A Feal Slim Glass 50 é uma solução minimalista que equilibra transparência, resistência estrutural e design funcional. Ideal para projetos residenciais que desejam amplificar a luminosidade natural, criar ambientes integrados e garantir uma estética contínua com o mínimo de interferência visual. Seu perfil delgado permite aplicações em vãos generosos, mantendo a leveza na percepção visual e a robustez necessária para suportar vidros de maiores espessuras com desempenho técnico garantido.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "23mm x 50mm" },
      { label: "Espessura do vidro", value: "12 a 20mm" },
      { label: "Acabamentos disponíveis", value: "Anodizado, pintura eletrostática e efeito madeira" },
      { label: "Tipologias", value: "Correr | Fixo " },
      { label: "Complementos compatíveis", value: "Persiana integrada e pinazio" },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 3,
    name: "FEAL SLIM GLASS 60",
    slug: "feal-slim-glass-60",
    category: "minimalista",
    categoryId: 1,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/feal-slim-60-hero.jpg",
    price: "R$ 3.850,00",
    description: "Minimalista | Tipologia: Correr e Fixo",
    integration: "Sistemas Feal Slim Glass 30 e Feal Slim Glass 50, mantendo uniformidade de linguagem visual",
    intdescrp: "Complementos externos como brises, muxarabis ou sistema camarão, conforme o conceito arquitetônico",
    titledesc: "Amplitude com precisão técnica",
    fullDescription:
      "A Feal Slim Glass 60 é a escolha certa para projetos que exigem grandes vãos com transparência total e design. Seu perfil minimalista, aliado a resistência e performance do vidro, resultam na solução ideal para o seu projeto. Projetada para integrar arquitetura e paisagem com harmonia, a Slim Glass 60 suporta folhas de vidro de maior espessura e peso, mantendo suavidade no uso, por conta dos componentes e exclusivos Tecnofeal.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "30mm x 60mm" },
      { label: "Espessura do vidro", value: "12 a 52mm" },
      { label: "Acabamentos disponíveis", value: "Todos os acabamentos disponíveis" },
      { label: "Tipologias", value: "Correr | Fixo" },
      { label: "Complementos compatíveis", value: "Persianas integradas e blackouts entre vidros,  tela mosquiteiras tensionadas e plissadas e pinázio." },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  // Categoria Conceito
  {
    id: 5,
    name: "FEAL SLIM 80",
    slug: "conceito-feal-slim-80",
    category: "conceito",
    categoryId: 2,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/conceito-80-hero.jpg",
    price: "R$ 4.850,00",
    description: "Linha Conceito | Tipologia: Correr, Fixo, Camarão, Giro",
    integration: "Linhas Feal Slim 100 e Slim 120, para continuidade estética",
    intdescrp: "-",
    titledesc: "Robustez discreta para grandes soluções",
    fullDescription:
      "A Feal Slim 80 oferece uma solução arquitetônica para projetos que exigem maior resistência estrutural sem abrir mão da elegância visual. Com perfis mais robustos e design limpo, essa linha é ideal para aplicações em vãos amplos que demandam múltiplas tipologias de abertura e máxima performance técnica. Seu desenho versátil permite combinações como sistemas camarão e giro, garantindo fluidez nos movimentos e conforto térmico — tudo com o acabamento refinado característico da Tecnofeal.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Fecho com cilindro na mão de amigo", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "48mm x 80mm" },
      { label: "Espessura do vidro", value: "8 a 12mm" },
      { label: "Acabamentos disponíveis", value: "Pintura eletrostática | Anodização | Efeito madeira" },
      { label: "Tipologias", value: "Correr | Fixo | Camarão | Giro" },
      { label: "Complementos compatíveis", value: "Persianas integradas, venezianas, tecido solar,  tela mosquiteiras tensionadas e plissadas" },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 6,
    name: "FEAL SLIM 100",
    slug: "conceito-feal-slim-100",
    category: "conceito",
    categoryId: 2,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/conceito-100-hero.jpg",
    price: "R$ 5.500,00",
    description: "Linha Conceito | Tipologia: Correr, Fixo, Pivotante",
    integration: "Linhas Feal Slim 80 e Slim 120, para continuidade  estética",
    intdescrp: "-",
    titledesc: "Versatilidade elegante com alta performance",
    fullDescription:
      "A Feal Slim 100 combina robustez, precisão e estética refinada em um sistema versátil, ideal para projetos que exigem estrutura reforçada com vista intermediária da esquadria. Sua construção permite suportar folhas de vidro maiores com segurança, mantendo fluidez de movimento, vedação eficiente e linguagem arquitetônica limpa. É uma solução que atende perfeitamente ambientes internos e externos com aberturas largas, fachadas contínuas ou passagens generosas, com a sofisticação que define a linha Conceito Feal Slim.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "52mm x 100mm" },
      { label: "Espessura do vidro", value: "12 a 48mm" },
      { label: "Acabamentos disponíveis", value: "Anodizado, pintura eletrostática e efeito madeira" },
      { label: "Tipologias", value: "Correr | Fixo | Pivotante" },
      { label: "Complementos compatíveis", value: "Persianas integradas, persianas blackouts ou entre vidros, tela solar e pinázio" },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 7,
    name: "FEAL SLIM 120",
    slug: "conceito-feal-slim-120",
    category: "conceito",
    categoryId: 2,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/conceito-120-hero.jpg",
    price: "R$ 6.200,00",
    description: "Linha Conceito | Edição Limitada",
    integration: "Linhas Feal Slim 80 e Slim 100 para continuidade estética",
    intdescrp: "-",
    titledesc: "Desempenho estrutural com estética refinada",
    fullDescription:
      "A Feal Slim 120 é uma solução desenvolvida para grandes vãos, folhas de vidro robustas e projetos com alto grau de exigência técnica e estética. Seu perfil profundo garante máxima resistência estrutural, mantendo o design elegante e a leveza visual características da linha Conceito. Ideal para fachadas residenciais de grande escala, a Slim 120 alia eficiência termoacústica, estanqueidade e liberdade de projeto, tornando-se uma escolha estratégica para arquitetos que buscam desempenho sem comprometer o visual.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "80mm x 120mm" },
      { label: "Espessura do vidro", value: "16 a 24mm" },
      { label: "Acabamentos disponíveis", value: "Anodizado, pintura eletrostática e efeito madeira" },
      { label: "Tipologias", value: "Correr | Fixo | Pivotante" },
      { label: "Complementos compatíveis", value: "Persianas integradas, blackouts ou entre vidros, pinázio" },
      { label: "Sistema de trilhos", value: "Captação de água embutida" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  // Categoria Premium
  {
    id: 9,
    name: "FEAL 40",
    slug: "classica-feal-40",
    category: "classica",
    categoryId: 3,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-200-hero.jpg",
    price: "R$ 8.500,00",
    description: "Linha Premium | Luxo e Sofisticação",
    fullDescription:
      "O Premium Elite 200 combina luxo e sofisticação com a mais alta tecnologia em esquadrias premium.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "200mm x 300mm" },
      { label: "Espessura do vidro", value: "Até 60 mm" },
      { label: "Acabamentos disponíveis", value: "Acabamentos de luxo" },
      { label: "Tipologias", value: "Premium personalizadas" },
      { label: "Complementos compatíveis", value: "Linha premium completa" },
      { label: "Sistema de trilhos", value: "Premium de luxo" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 10,
    name: "FEAL 55",
    slug: "classica-feal-55",
    category: "classica",
    categoryId: 3,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-250-hero.jpg",
    price: "R$ 9.800,00",
    description: "Linha Premium | Exclusividade Máxima",
    fullDescription: "O Premium Elite 250 oferece exclusividade máxima com acabamentos únicos e tecnologia de ponta.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "250mm x 350mm" },
      { label: "Espessura do vidro", value: "Até 64 mm" },
      { label: "Acabamentos disponíveis", value: "Exclusivos premium" },
      { label: "Tipologias", value: "Sob medida exclusivas" },
      { label: "Complementos compatíveis", value: "Tecnologia premium" },
      { label: "Sistema de trilhos", value: "Exclusivo premium" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 11,
    name: "FEAL 75",
    slug: "classica-feal-75",
    category: "classica",
    categoryId: 3,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-300-hero.jpg",
    price: "R$ 11.500,00",
    description: "Linha Premium | Obra de Arte",
    fullDescription:
      "O Premium Elite 300 é uma verdadeira obra de arte em esquadrias, desenvolvido para projetos únicos e exclusivos.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "300mm x 400mm" },
      { label: "Espessura do vidro", value: "Até 68 mm" },
      { label: "Acabamentos disponíveis", value: "Artísticos exclusivos" },
      { label: "Tipologias", value: "Obras de arte" },
      { label: "Complementos compatíveis", value: "Arte e tecnologia" },
      { label: "Sistema de trilhos", value: "Obra de arte" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 12,
    name: "FEAL 100",
    slug: "classica-feal-350",
    category: "classica",
    categoryId: 3,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 13,
    name: "FEAL 160",
    slug: "corporativo-feal-160",
    category: "corporativo",
    categoryId: 4,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 14,
    name: "FEAL 130",
    slug: "corporativa-feal-130",
    category: "corporativo",
    categoryId: 4,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 15,
    name: "BRISE ARQUITETÔNICO",
    slug: "corporativo-brise-arquitetonico",
    category: "corporativo",
    categoryId: 4,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 16,
    name: "FEAL 100",
    slug: "corporativo-feal-100",
    category: "corporativo",
    categoryId: 4,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 17,
    name: "FEAL WIDE 4000",
    slug: "feal-wide-4000",
    category: "complementares",
    categoryId: 5,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 18,
    name: "MUXARABI",
    slug: "muxarabi",
    category: "complementares",
    categoryId: 5,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 19,
    name: "RIPADOS",
    slug: "ripados",
    category: "complementares",
    categoryId: 5,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },
  {
    id: 20,
    name: "BLACKOUT",
    slug: "blackout",
    category: "complementares",
    categoryId: 5,
    image: "/image/produtos/produtos-placeholder.png",
    heroImage: "/images/products/premium-350-hero.jpg",
    price: "R$ 13.200,00",
    description: "Linha Premium | Coleção Limitada",
    fullDescription:
      "O Premium Elite 350 é nossa coleção limitada, representando o ápice da engenharia e design em esquadrias.",
    componentesExclusivos: [
      { texto: "Roldanas com rolamento inox blindado, que garantem suavidade ao abrir e fechar", imagem: "/image/produtos/componentes-icon1.png" },
      { texto: "Compatibilidade com acessórios personalizados e projetos sob medida", imagem: "/image/produtos/componentes-icon2.png" },
      { texto: "Gaxetas em silicone que contribuem para estanqueidade.", imagem: "/image/produtos/componentes-icon3.png" },
      { texto: "Acessórios exclusivos desenhados para a linha", imagem: "/image/produtos/componentes-icon4.png" },
    ],
    technicalDetails: [
      { label: "Dimensões (Vista x profundidade)", value: "350mm x 450mm" },
      { label: "Espessura do vidro", value: "Até 72 mm" },
      { label: "Acabamentos disponíveis", value: "Coleção limitada" },
      { label: "Tipologias", value: "Únicas no mundo" },
      { label: "Complementos compatíveis", value: "Exclusivos limitados" },
      { label: "Sistema de trilhos", value: "Coleção limitada" },
    ],
    openingTypes: [
      { name: "2 folhas", image: "/image/produtos/duasfolhas.png" },
      { name: "3 folhas", image: "/image/produtos/tresfolhas.png" },
      { name: "4 folhas", image: "/image/produtos/quatrofolhas.png" },
      { name: "2 folhas com persiana integrada", image: "/image/produtos/ultimo.png" },
    ],
  },

]

// Função para obter produtos por categoria
export const getProductsByCategory = (categorySlug: string) => {
  return products.filter((product) => product.category === categorySlug)
}

// Função para obter produto por slug
export const getProductBySlug = (slug: string) => {
  return products.find((product) => product.slug === slug)
}

// Função para obter categoria por slug
export const getCategoryBySlug = (slug: string) => {
  return productCategories.find((category) => category.slug === slug)
}
