import type { Metadata } from "next";
import localfont from "next/font/local";

import "./globals.css";

const belfastGrotesk = localfont({
  src: [
    {
      path: "../../public/fonts/BelfastGroteskLight.ttf",
      weight: "300",
    },
    {
      path: "../../public/fonts/BelfastGroteskRegular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/BelfastGroteskSemiBold.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/BelfastGroteskBold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/BelfastGroteskBlack.ttf",
      weight: "900",
    }
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${belfastGrotesk} antialiased bg-primary-grey`}>
        {children}
      </body>
    </html>
  );
}
